-- Run this in your Supabase SQL Editor to create the missing certificates table!

CREATE TABLE certificates (
  id bigint generated by default as identity primary key,
  event_id bigint references events on delete cascade not null,
  file_name text not null,
  mime_type text not null,
  storage_path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;

-- Users can only manage certificates for events they own
CREATE POLICY "Users can view own certificates metadata" 
ON certificates FOR SELECT 
USING ( EXISTS (SELECT 1 FROM events WHERE events.id = certificates.event_id AND events.user_id = auth.uid()) );

CREATE POLICY "Users can insert own certificates metadata" 
ON certificates FOR INSERT 
WITH CHECK ( EXISTS (SELECT 1 FROM events WHERE events.id = certificates.event_id AND events.user_id = auth.uid()) );

CREATE POLICY "Users can delete own certificates metadata" 
ON certificates FOR DELETE 
USING ( EXISTS (SELECT 1 FROM events WHERE events.id = certificates.event_id AND events.user_id = auth.uid()) );
